//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAMA.Web {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal AppString() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wama.web.AppString", typeof(AppString).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Account approval pending. Please contact front desk..
        /// </summary>
        public static string AccountPendingApprovalMessage {
            get {
                return ResourceManager.GetString("AccountPendingApprovalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your account has been suspecded! Please contact the front desk..
        /// </summary>
        public static string AccountSuspended {
            get {
                return ResourceManager.GetString("AccountSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No user account has the member ID {0}..
        /// </summary>
        public static string AccountWithIdDoesntExist {
            get {
                return ResourceManager.GetString("AccountWithIdDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Account with same member ID {0} already exist.
        /// </summary>
        public static string AccountWithSameMemberIdExist {
            get {
                return ResourceManager.GetString("AccountWithSameMemberIdExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Administrator.
        /// </summary>
        public static string AdministratorLabel {
            get {
                return ResourceManager.GetString("AdministratorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your cerficate has been expired..
        /// </summary>
        public static string CertificateExpired {
            get {
                return ResourceManager.GetString("CertificateExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Controller.
        /// </summary>
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Employee.
        /// </summary>
        public static string EmployeeLabel {
            get {
                return ResourceManager.GetString("EmployeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ErrorMessages.
        /// </summary>
        public static string ErrorMessages {
            get {
                return ResourceManager.GetString("ErrorMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Hmm! Seems like something weird happened, please try again in a few..
        /// </summary>
        public static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Manager.
        /// </summary>
        public static string ManagerLabel {
            get {
                return ResourceManager.GetString("ManagerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No account with member ID {0} exists. Create a new account..
        /// </summary>
        public static string NoAccountExistsWithID {
            get {
                return ResourceManager.GetString("NoAccountExistsWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Patron.
        /// </summary>
        public static string PatronLabel {
            get {
                return ResourceManager.GetString("PatronLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Signature does not match with the name of the Patron. Please sign using the following format: First Name Last Name.
        /// </summary>
        public static string SignatureMismatch {
            get {
                return ResourceManager.GetString("SignatureMismatch", resourceCulture);
            }
        }
    }
}
